apiVersion: v1
kind: Secret
metadata:
  name: keda-kafka-secrets
  namespace: default
data:
  sasl: "cGxhaW50ZXh0" # No need to change
  username: "<base64 coded API key username>"
  password: "<base64 coded API key password>"
  tls: "ZW5hYmxl" # No need to change
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-kafka-credential
  namespace: default
spec:
  secretTargetRef:
  - parameter: sasl
    name: keda-kafka-secrets
    key: sasl
  - parameter: username
    name: keda-kafka-secrets
    key: username
  - parameter: password
    name: keda-kafka-secrets
    key: password
  - parameter: tls
    name: keda-kafka-secrets
    key: tls
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: kafka-keda
  pollingInterval: 5
  maxReplicaCount: 12
  cooldownPeriod:   120
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: <Broker host>
      consumerGroup: group-8       # Make sure that this consumer group name is the same one as the one that is consuming topics
      topic: kedaongke
      lagThreshold: "20"
      offsetResetPolicy: latest
    authenticationRef:
      name: keda-trigger-auth-kafka-credential
